services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres
    networks:
      - db_net

  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORTS}
    networks:
      - db_net

volumes:
  postgres_data:

networks:
  db_net:
    driver: bridge
