services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - db_net

  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORTS}
    networks:
      - db_net

volumes:
  postgres_data:

networks:
  db_net:
    driver: bridge
